spring.application.name=UserWeb20260907
# 伺服器埠號（預設 8080）
server.port=8080
# session保留與否
server.servlet.session.persistent=false

# MySQL 資料庫連線設定（請依據你的環境修改密碼）
spring.datasource.url=jdbc:mysql://localhost:3306/company
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 最多 30 條 DB Connection
spring.datasource.hikari.maximum-pool-size=30
# 借出超過 20 秒還沒歸還 → Leak 警告
spring.datasource.hikari.leak-detection-threshold=20000
# 拿不到 Connection 時最多等 30 秒
spring.datasource.hikari.connection-timeout=30000

# JPA / Hibernate 設定
# update create-drop validate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#排序PK放第一，後續用字母循序
spring.jpa.properties.hibernate.column_ordering_strategy=legacy


# MyBatis 會掃描您指定的包以及其子包下的所有 Java 類別
mybatis.type-aliases-package=com.example.demo.model

# 駝峰命名自動對應功能開啟 (ex: user_name -> userName)
mybatis.configuration.map-underscore-to-camel-case=true

# 指定 Mapper XML 檔案位置
mybatis.mapper-locations=classpath:mapper/**/*.xml

# 設定自動對應的行為等級
mybatis.configuration.auto-mapping-behavior=FULL

# Keys.hmacShaKeyFor(secretKeyStr.getBytes())需要256位元
jwt.secret-key=1234567890abcdefghij1234567890ab
jwt.private-key=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfO9Jk5du3NMBvikcJQBLPrUkMYadujZ1PYs+ytVqcuOC2AuOZ7HGrrS0v4objEo1c6x83CVvF9my2tZzhGdg4StqxFvbqlvhg1LkJO8vsXThN119wSjKm8JjmV4ZcwDYddqnnbPtyzJ57QYWmf8niQeDElG4DuznuZdSKJqoJv+ROkkzG9Ahq32BfxcF7KazTwHLrCSbsqORJi+KnFh4UiuhdJs0x9H6DBZk4IN4g72HW2iLDmi5XH4r0YS4YsEY4VQqg5rUidjuT0buElUMDe3k8XmImHgprt6iREM5CfNEBVx5/9/m5Iwk8Ux2uLwLaip4yUJv2vNTorSOlaCnNAgMBAAECggEAAlVtnXXy9OnsghX8OYn7XJjVD73kps2jhxTTJ3LZ+58ICBLdxBU/iz0UAvYmdPCCKuD1Sai09B9K85iQzonC7fxG3T6RatnAlSa4+YYrVHD/UMC90Nb9jA3Np96ThQt6H49sKQyjWMjf772DmG+aBVti0G6+eAaH8FMEvOuZJWBpLKSvjXWatax7sYrofNV8w3SE/2TPCCKZ9hbCYTInJODPJ0C5Rgs/h90eKqUVD5iz6Xm0ZdaEDQ99/Xz7RPlIFF5aMCxbpTXdkEsyAw9HKvbxtad/JtUxX9zq0vYsj9uyiK0OmI9hqS3bjLmFxy9UnWdf1cxYwVubD0zlnRLtAQKBgQDJ+l3q0bbIfpl5H/cZdLPDkHA3iYh2WCBQebSPAgBPxPwtz+fnJ8Y1G8gsGxA2QYjRdZFuGrB/n9ImeWlSo+zxtSjdD2ky5vcxoYKmmR0dAwhRRAQS2r2NFKKC7YouEv6ct4cneZWfewHST1QOVtkPmumxvzGzretvm7SkJKuQTQKBgQDJ0rWYsNVCP2Dbpf5bVX4lx7PK7eGXrMCFxLivNYja9mqbFb2gI1ykhqaQOaaF17v74GL+E64kol5Nsov6YqAiXXofTWFOG6St87SuPRU0urkSwUKB2M+1sihJhOAsPMAQvZgwKfi/o/A+5lBZpap+LiyFQeXbK4l0hI2ksPe/gQKBgQCgCu1EVix5ric6HSQVXa3btqXUu/wPmkDww59Y+gL5MmOIgYeGWLPr/TmeCUvNUhxxrLEyB5/3YNKKfgYA37euxxe8Iqv/E5ioEQyPqh+xj2eVzUlVD1LHaaRkDolBfPeXgq1rkCIJHtUQqp82RYb1oJCwsYlWkOdPppd6wTvYuQKBgCl+WruTz6SZJy7Bh/P7Nb5KuppEIhdu+v4FnfrXxNVPyEcuRxg/bPKehGwujiACZLG6Rl/6Z9k8UKskxEasNEQcd9krrY/Dey4QZttTz6JRqW9DsIrFqp6ujD3hRb2Sl+JZOIredjfgWqpz650ixFTA5YJYNAvFfbMo9X4grC8BAoGAEWiSzDV+YyiNOaAowbbSDZRpBUsMgxNZ4HL9bvaXZ79GlbJMqyx4Qkpd7AqnR0F5oDnD8+uDhxDhG+xDYcDn5GpBrXd8Qu1JYCuZ2nLYne0pOg4VfvHzQyaOpvomq9wwUj1vJNtRBwZwgcqPZ9mhWoYUglVoUF1YthwjL0rK1ZI=
jwt.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzvSZOXbtzTAb4pHCUASz61JDGGnbo2dT2LPsrVanLjgtgLjmexxq60tL+KG4xKNXOsfNwlbxfZstrWc4RnYOErasRb26pb4YNS5CTvL7F04TddfcEoypvCY5leGXMA2HXap52z7csyee0GFpn/J4kHgxJRuA7s57mXUiiaqCb/kTpJMxvQIat9gX8XBeyms08By6wkm7KjkSYvipxYeFIroXSbNMfR+gwWZOCDeIO9h1toiw5ouVx+K9GEuGLBGOFUKoOa1InY7k9G7hJVDA3t5PF5iJh4Ka7eokRDOQnzRAVcef/f5uSMJPFMdri8C2oqeMlCb9rzU6K0jpWgpzQIDAQAB
jwt.access-valid-seconds=60
jwt.refresh-valid-seconds=600

